# Generated by Django 5.0.3 on 2024-03-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_admin_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
