# Generated by Django 5.0.3 on 2024-03-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotellist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotellist',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
