# Generated by Django 5.0.3 on 2024-03-26 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookinghotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('contact_no', models.CharField(max_length=13)),
                ('no_people', models.IntegerField()),
                ('no_rooms', models.IntegerField(default=0)),
                ('start', models.DateField(default=None)),
                ('end', models.DateField(default=None)),
                ('username', models.CharField(max_length=30)),
                ('useremail', models.EmailField(default=None, max_length=50)),
                ('userpassword', models.CharField(max_length=200)),
                ('hotelname', models.CharField(default=None, max_length=80)),
                ('city', models.CharField(default=None, max_length=60)),
                ('state', models.CharField(default=None, max_length=60)),
                ('current_cost', models.FloatField(default=0.0)),
                ('payment_status', models.CharField(default='Unpaid', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('useremail', models.EmailField(max_length=50)),
                ('contact_no', models.CharField(max_length=13)),
                ('querydetails', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('querystatus', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=50)),
            ],
        ),
    ]
